### ISSUE TITLE
Need help with packaging Midori on a system with the latest version of GTK+ and Vala

### ISSUE THREAD

**Issue by xyproto** [midori-browser/core#108]
Hi,

I'm maintaining Midori for Arch Linux. After GTK+ was updated beyond 3.10, the latest release of Midori no longer builds.

`midori`: 0.5.11
`gtk3`: 3.24.1
`webkit2gtk`: 2.22.2

I have tried to patch Midori heavily with the following shell commands:

```bash
sed 's/protected Tally/public Tally/g' -i midori/midori-notebook.vala
sed 's/%d other files/%u other files/g' -i extensions/transfers.vala
for f in transfers adblock/widgets apps history-list notes; do
  sed 's,.remove (iter,.remove (ref iter,g' -i "extensions/$f.vala"
done
find . -type f -regex '.*\.\(c\|vala\)' -exec sed -i \
    's/Gtk.STOCK_FILE/"text-x-generic"/g;s/Gtk.STOCK_CLOSE/"window-close"/g;s/Gtk.STOCK_ADD/"list-add"/g;s/Gtk.STOCK_HELP/"help-browser"/g;s/Gtk.STOCK_APPLY/""/g;s/Gtk.STOCK_CANCEL/""/g;s/Gtk.STOCK_COPY/"edit-copy"/g;s/Gtk.STOCK_DELETE/"edit-delete"/g;s/Gtk.STOCK_EDIT/""/g;s/Gtk.STOCK_OPEN/"document-open"/g;s/Gtk.STOCK_PREFERENCES/"preferences-system"/g;s/Gtk.STOCK_PROPERTIES/"document-properties"/g;s/Gtk.STOCK_SAVE/"document-save"/g;s/Gtk.STOCK_CLEAR/"edit-clear"/g;s/Gtk.STOCK_DIRECTORY/"folder"/g' \
    "{}" +;
find . -type f -regex '.*\.\(c\|vala\)' -exec sed -i \
    's/g_dbus_generate_guid/GLib.DBus.generate_guid/g' "{}" +;
```

This makes Midori build again, and it works fine for many webpages, but fails when first opening a webpage in a tab, then closing midori and then opening midori again. For instance with `https://news.ycombinator.com/`.

The error in the console is:

```
** (midori4:18219): CRITICAL **: 11:19:31.096: gboolean webkit_web_view_get_tls_info(WebKitWebView*, GTlsCertificate**, GTlsCertificateFlags*): assertion 'wkCertificateInfo' failed
```

I am building with `-DHALF_BRO_INCOM_WEBKIT2=ON`.

My goal is to package Midori so that it works together with the latest version of GTK+ and is as stable as possible.

Do you have any upcoming patches that could help me out here?

Best regards,
Alexander F. Rødseth

**Comment by kalikiana** [comment]
Hey Aelxander,

Thanks for reaching out! The upcoming release should be faring much better with regard to the issues you've mentioned because the core has been revamped, with higher minimum requiremnts and GTK+3/WebKit2 being the only supported option. Would you mind giving git master a go?

**Comment by xyproto** [comment]
Building from latest master works, but I get quite a few of these:

    (midori:25104): Gtk-CRITICAL **: 13:47:11.759: gtk_render_frame_gap: assertion 'xy1_gap <= width' failed

**Comment by xyproto** [comment]
Using latest master for the Arch Lunux package until the next release of Midori.

**Comment by kalikiana** [comment]
FYI Midori 6 has now been released.

**Comment by nmcain** [comment]
Hi, I am also trying to build this version of midori, on my embedded system, @xyproto do you still maintain versions of the source compatible with the latest GTK?

**Comment by xyproto** [comment]
@nmcain No, I only maintain the Arch Linux package for the latest release version of Midori and Gtk. This PKGBUILD works with the latest version of Gtk if it's any help? https://github.com/archlinux/svntogit-community/blob/d921012b362aedcf6058fc594791e00e92872e6d/trunk/PKGBUILD

**Comment by nmcain** [comment]
Ah, thanks. I'm getting errors with the latest version of it, 0.5.11 always
had been stable for me.
