### ISSUE TITLE
Release tarball does not contain top directory

### ISSUE THREAD

**Issue by mgorny** [midori-browser/core#150]
Hi,

It seems that the new release tarball for v6.0 lacks top directory and instead extracts everything to the current directory. This is not what Linux users expect from tarballs, and it is really horrible to people who happen to extract it in some unexpected directory.

In other words, `tar -tf midori-v6.0.tar.gz` is:
```
.circleci/
.circleci/config.yml
.gitignore
CMakeLists.txt
COPYING
```

while it should be:
```
midori-v6.0/.circleci/
midori-v6.0/.circleci/config.yml
midori-v6.0/.gitignore
```
etc.

**Comment by kalikiana** [comment]
I guess the `--prefix` option with `git archive` will do the job - truth be told I didn't realize because my tooling of choice handles that automatically. That said I'm happy to adjust the tarball generation accordingly.

**Comment by mgorny** [comment]
Thanks. I'm using plain `tar -xf ...` to extract the sources for diff-ing.

**Comment by wyatt8740** [comment]
Should probably rename this issue '6.0 release is a tarbomb.'
This just bit me, too.
