### ISSUE TITLE
Installation from source faillure

### ISSUE THREAD

**Issue by pmraps** [midori-browser/core#157]
Hi,
got this building from [midori-v6.0.tar.gz](https://github.com/midori-browser/core/releases/download/v6/midori-v6.0.tar.gz) on MX17(debian) 32 bit:

`cmake -DCMAKE_INSTALL_PREFIX=/usr ..
-- valac 0.34.7 found
CMake Error at cmake/ValaPrecompile.cmake:235 (add_custom_command):
  add_custom_command Wrong syntax.  A TARGET or OUTPUT must be specified.
Call Stack (most recent call first):
  extensions/CMakeLists.txt:28 (vala_precompile)

You have called ADD_LIBRARY for library CMakeFiles without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Skipping CMakeLists.txt
-- Skipping adblock.plugin.in
-- Skipping bookmarks.plugin.in
-- Skipping colorful-tabs.plugin.in
-- Skipping session.plugin.in
-- Skipping status-clock.plugin.in
-- Skipping statusbar-features.plugin.in
-- gettext found: af am ar ast az be bg bn bs ca ckb cs cy da de el en_AU en_CA en_GB eo es et eu fa fi fr gd gl he hi hr hu ia id it ja ka kk km ko ku ky lb lt lv ml ms nap nb nl nn no pa pl pt pt_BR ro ru sk sl sq sr sr@latin sv szl ta te th tl tr ug uk ur uz vi zh_CN zh_HK zh_TW 
-- Configuring incomplete, errors occurred!
See also "/home/pmralbuquerque/Programas/midori/CMakeFiles/CMakeOutput.log".
`

**Comment by kalikiana** [comment]
It looks like you tried to build directly within the source folder. Please see [the steps outlined in README.me](https://github.com/midori-browser/core#building-from-source) which show how to create a separate build folder.

**Comment by kalikiana** [comment]
I'm going to propose a fix to make this error more obvious. But as far as this issue is concerned the solution is to build the recommended way.

**Comment by pmraps** [comment]
Sorry but it's not that. I included the path. Check it out:

`pmralbuquerque@pmra:~/Programas/**midori/_build**
$ cmake -DCMAKE_INSTALL_PREFIX=/usr ..
-- valac 0.34.7 found
CMake Error at cmake/ValaPrecompile.cmake:235 (add_custom_command):
  add_custom_command Wrong syntax.  A TARGET or OUTPUT must be specified.
Call Stack (most recent call first):
  extensions/CMakeLists.txt:28 (vala_precompile)


You have called ADD_LIBRARY for library CMakeFiles without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Skipping CMakeLists.txt
-- Skipping adblock.plugin.in
-- Skipping bookmarks.plugin.in
-- Skipping colorful-tabs.plugin.in
-- Skipping session.plugin.in
-- Skipping status-clock.plugin.in
-- Skipping statusbar-features.plugin.in
-- gettext found: af am ar ast az be bg bn bs ca ckb cs cy da de el en_AU en_CA en_GB eo es et eu fa fi fr gd gl he hi hr hu ia id it ja ka kk km ko ku ky lb lt lv ml ms nap nb nl nn no pa pl pt pt_BR ro ru sk sl sq sr sr@latin sv szl ta te th tl tr ug uk ur uz vi zh_CN zh_HK zh_TW 
-- Configuring incomplete, errors occurred!
See also "/home/pmralbuquerque/Programas/midori/CMakeFiles/CMakeOutput.log".
`

**Comment by kalikiana** [comment]
@pmraps I can see at the very end of your log a reference to `[...]/Programas/midori/CMakeFiles` which suggests it's writing files to the source and not to the `_build` folder.

**Comment by pmraps** [comment]
I would bet, not being a developer, on the first error:
> CMake Error at cmake/ValaPrecompile.cmake:235 (add_custom_command)

So, where is the error? What do I do to fix it?

**Comment by kalikiana** [comment]
If you built inside the source previously and tried to use a `_build` folder, CMake is probably finding the old files.
I suggest you remove the folder and start from scratch.

  mkdir _build
  cd _build
  cmake -DCMAKE_INSTALL_PREFIX=/usr ..

The most important step here is to create the build folder first and never to run CMake in the original source folder.

**Comment by pmraps** [comment]
Ok, rm -rf all, extracted again and everything is running, so it should be OK. Thank you for the help! :)
