### ISSUE TITLE
Change name 

### ISSUE THREAD

**Issue by Poncho09** [midori-browser/core#179]
Midori have problem with the name why when looking in Google, Bing, Yahoo etc Midori the japanese term that appears stationery and cloth. Midori Browser is something spectacular has more than 8 million results in Google but when searching for alternative browsers it keeps getting lost, then what is the proposal to change the name something that is original and easy to remember in order to migrate little by little there and serve rebirth.

My Proposal:

> Vexty.

With little results in google 
> Neption

**Comment by kalikiana** [comment]
To be frank I don't think changing the name is a good idea considering it's been around for a decade now.

What we can certainly play with is nicknames (cf. Midori Fortress, Firefox Quantum, Chrome Canary)
