### ISSUE TITLE
No visible cursor in input text boxes

### ISSUE THREAD

**Issue by CodyRude** [midori-browser/core#181]
I am having trouble where there is no visible cursor when entering text into a textbox. For example, entering a search query at duckduckgo.com. Interestingly enough I do have a visible cursor when entering a url.

Steps to reproduce:

1. Go to duckduckgo.com
2. Click the mouse on the search box

Expected results:
1. A visible cursor in the text box indicating where text will be entered

Actual results:
1. No visible cursor. Entering text still works, just without the cursor.

I'm on Arch Linux, Midori 6.0 and webkit2gtk 2.22.4

**Comment by kalikiana** [comment]
@CodyRude Thanks for the report! I opened a PR with a fix.

**Comment by CodyRude** [comment]
@kalikiana I tried the fix and it works great. Thanks!
