### ISSUE TITLE
Accepting self signed certificate

### ISSUE THREAD

**Issue by CodyRude** [midori-browser/core#182]
My apologies if this is a user error and not an actual bug. I tried to ensure I was following the correct steps to accept a self signed certificate.

The administration webpage on my router has a self signed certificate. I followed the instructions in the FAQ located at https://wiki.xfce.org/midori/faq in order to enable self signed certificates but have been unable to access my routers webpage.

Steps to reproduce:
1. Enable accepting of self signed certificates as per the FAQ located in https://wiki.xfce.org/midori/faq
2. Go to a website with a self signed certificate such as https://selfsigned.notyours.dk:444/menu.gif
3 Click on the lock next to the url in order to accept the certificate
Expected results:
1. Be able to accept the self signed certificate
Actual results:
1. A popup containing the text "Security unknown" is displayed with no option to enabled self signed certificates

I'm on Arch Linux with Midori 6.0. The Arch package (information at https://www.archlinux.org/packages/community/x86_64/midori/ ) lists gcr is a dependency, so I'm assuming Midori was compiled with gcr support.

**Comment by kalikiana** [comment]
You're absolutely correct. This indeed looks to be a regression.

**Comment by gklimm** [comment]
@CodyRude gnome-keyring-daemon is running?

**Comment by CodyRude** [comment]
Yep, I checked and the process running. I believe it is working as other applications can save their password.

**Comment by mathieu-aubin** [comment]
midori 7.0 on fedora 29 does the same

**Comment by mozai** [comment]
Seeing this in Midori 7.0 on Ubuntu 19.04 - clicking on padlock conjures a "Security Unknown" tooltip and nothing else.

**Comment by tkb11** [comment]
same thing with Midori 7.34 on RHEL7.6 - are there any workarounds?
