### ISSUE TITLE
Page not found overwrites Speed Dial entry

### ISSUE THREAD

**Issue by asc-soc** [midori-browser/core#188]
Trying to open a page from the speed dial that can't be accessed results in replacement of its title in speed bar with "page not found" (or localization thereof), and sometimes deletion of the page icon.
Expected behaviour is keeping the history entry / speed dial entry intact.

**Comment by kalikiana** [comment]
This seems to be a symptom of errors being recorded in history just like regular websites. #187 actually fixes that.
