### ISSUE TITLE
Clear private data: cancel/close button

### ISSUE THREAD

**Issue by asc-soc** [midori-browser/core#191]
In the "clear private data" dialog, I propose the label on the "cancel" button to change to "close" when all background tasks are complete (i.e., the "clear" button becomes active).

**Comment by asc-soc** [comment]
Or, for consistency with other dialogs, a close button [X] should be displayed at the top right corner.

**Comment by kalikiana** [comment]
I'm not sure I understand the distinction you're suggesting here. Cancel here mean to back out of whatever the dialog was going to do, and once all data has been populated the user still hasn't done anything...

The Cancel button actually acts as the close button with CSD enabled - conversely there's no way to explain or rename a server-side close button.

**Comment by asc-soc** [comment]
I understood “cancel” in a more technical sense to cancel the background task(s). You're right, I can (also) be taken as to cancel the whole private-data-clearing business and dismiss the dialog window.
