### ISSUE TITLE
Private browsing tabs not green

### ISSUE THREAD

**Issue by asc-soc** [midori-browser/core#200]
If a private browsing window has multiple tabs, they are not green but in the default app background colour. Maybe this is what is desired?

**Comment by kalikiana** [comment]
Do you have any suggestions?

**Comment by kalikiana** [comment]
Tabs have the theme color, while the titlebar is "private browsing" styled. I'm closing this since there was no more activity here. Feel free to re-open with a concrete proposal for a different design.
