### ISSUE TITLE
Merge app menu and page menu buttons

### ISSUE THREAD

**Issue by kalikiana** [midori-browser/core#204]
Something that has come up in several conversations, and which I was referring to in #193 is the request to merge the app and page menu buttons.

The current design aims to distinguish between global and website-specific actions. However some users have found this unclear. And there's the argument hat one button in the toolbar takes away less space from the tabbar.

Some data points:
- App menu/ settings for most GTK+ apps are on the right of the headerbar
- fullscreen is usually on the right eg. EOG, Builder
- Non-GTK+ browsers like Firefox/ Chrome place the menu in the toolbar
- Tab-specific actions go in the addressbar
- For web apps the addressbar is hidden
- Two buttons consume more space than one (d'uh)

This bug first of all serves to record the various discussions around this. The people involved will know who they are, but everyone is welcome to add their two cents here.

**Comment by Mau-G** [comment]
I think they are all good points. Personally I would be in favour for making this changes or make them somehow an option for packagers to adopt or not.

**Comment by kalikiana** [comment]
![photo_2018-11-21_08-50-46](https://user-images.githubusercontent.com/1204189/53769915-a2b55c80-3edd-11e9-8b37-962d0daba34c.jpg)
Mockup created some time ago. This will of course need to account for the new zoom menu introduced in #212 and buttons moving into the menu(s) with a small window.
