### ISSUE TITLE
Speed Dial: Images/thumbnails look distorted or sized wrong

### ISSUE THREAD

**Issue by Mau-G** [midori-browser/core#206]
Images don't have a fixed size and look distorted when Midori is maximised or window is resized.
See screenshot.

![screenshot_2018-12-05_22-45-00](https://user-images.githubusercontent.com/44322817/49521009-6c1c7580-f8df-11e8-9f3a-90eea55e0758.png)

**Comment by asc-soc** [comment]
I've been looking into the same issue for a while. So far, I do not have a definitive solution that works equally well for small bit-map icons and vector-graphics ones. Obviously, one would like to see neither small nor very pixel-y graphics.
The layout and image size policy is controlled by a CSS file (as the speed dial is just a generated HTML document).

**Comment by Mau-G** [comment]
I think something like this would look neat. Small icon + text and webpage screenshot underneath or just the small icon with text in tab style.


![screenshot_2018-12-06_12-40-15](https://user-images.githubusercontent.com/44322817/49561929-58f7bd00-f954-11e8-803e-645a2673d263.png)

**Comment by kalikiana** [comment]
We could split this issue. First to address the sizing, which is what it originally was about. And then make a new one to add screenshot management.
