### ISSUE TITLE
System wide plugins not loaded from same directories

### ISSUE THREAD

**Issue by ryu0** [midori-browser/core#218]
I noticed that the main process and session processes for midori don't look for system wide plugins in the same location. Effectively, one looks for them in Config.PLUGINDIR whereas the other looks for them in (exec_path)/../lib/midori. If this is considered a bug, I can make the necessary fixes to make both use Config.PLUGINDIR.

**Comment by kalikiana** [comment]
Could you elaborate a bit on that? How is Midori run (paths) and what is going wrong?

**Comment by ryu0** [comment]
See core/app.vala in the default branch. At line 113 and 163, Config.PLUGINDIR is used to determine which directory to use when loading plugins. However, at line 121 (within a lambda function), the code doesn't use Config.PLUGINDIR, and instead derives it from the directory that midori is run from.

In my case, it's at /usr/bin/midori, which ends up looking for plugins under /usr/lib/midori, which is not the same as Config.PLUGINDIR in my case because Debian insists on using /usr/lib/x86_64-linux-gnu/midori. The end result is that some plugins, such as adblock, do not work due to this code not finding them when it is run.

**Comment by kalikiana** [comment]
At the back of my head I was thinking this description of the arch-specific folder seems familiar... after going through closed issues it seems to me that #168 was incomplete! [core/app.vala:121](https://github.com/midori-browser/core/blob/de3e22e3122fa8fb1e793f0d010cc73a448dcc88/core/app.vala#L121) should be using `Config.PLUGINDIR` as well!
