### ISSUE TITLE
Debian/Ubuntu source package files

### ISSUE THREAD

**Issue by ryu0** [midori-browser/core#223]
I managed to create a Debian/Ubuntu source package for Midori, though I had to create some patches to fix some issues. Is there any interest in accepting a source package into this upstream repository?

**Comment by kalikiana** [comment]
Please open issues for here for any problems you encounter and we can look into getting rid of those patches.

As a general rule of thumb distro packaging should be left to distros.

Also note that [Debian re-added the package](https://packages.debian.org/unstable/main/midori). You may want to talk to @NatureShadow
