### ISSUE TITLE
Reporting bugs made unnecessarily hard

### ISSUE THREAD

**Issue by ohreally** [midori-browser/core#228]
The 'Report a problem' option in the menu sends me to https://bugs.launchpad.net/midori. That page says 'Bugs are tracked in Github Issues Tracker.', and the last 3 words are a link. But that link leads nowhere.
I'd say, make the menu option point at https://github.com/midori-browser/core/issues.

**Comment by kalikiana** [comment]
Going by #229 I'm assuming this is with 0.5.7 built against WebKit2. The latest version doesn't have the menu.

Although maybe we should re-consider adding the menu back?

**Comment by ohreally** [comment]
Well, actually this is 0.5.11 on Fedora Linux. On the utter right side of the location bar there is a button (icon: file with wrench) which opens a menu. One of the options in that menu is 'Report a problem...' (translated from Dutch).

**Comment by ohreally** [comment]
Okay, Midori is at version 7 already; hadn't noticed.

**Comment by ohreally** [comment]
To answer your question...
Instead of re-adding a menu item for reporting problems, you could also add it to the info dialog. This would allow you to keep your menu small, while still inviting users to report bugs/problems.

**Comment by kalikiana** [comment]
I like the idea of putting it into the About dialog and went ahead with putting up a PR with that. Thanks for the suggestion!
