### ISSUE TITLE
Cancelling a download crashes Midori

### ISSUE THREAD

**Issue by ohreally** [midori-browser/core#229]
Title says it all.
Go to any site where you can download files, and click a download link. Then, when the dialog pops up that asks whether to save the file, click Cancel. Browser crashes.

Oh, by the way: using Midori 0.5.11 on Fedora Linux.

**Comment by ohreally** [comment]
Good question.
Actually, it is impossible to cancel an active download.
The active download is visible in the status bar, with a red cross next to it. I guess it should be possible to cancel the download by clicking the red cross. But no matter how often I click, the download just continues.

**Comment by kalikiana** [comment]
Any chance you can try with a newer version?

**Comment by ohreally** [comment]
Ah, I'm sorry. I see Midori is at version 7 already, and Fedora is way behind.
I hadn't noticed. I will refrain from reporting bugs from now on.

And no, no chance I can try with a newer version. To keep my system clean, I will only install software from the official repositories.

Sorry.

**Comment by kalikiana** [comment]
I don't know what version you're on... but updated packages exist. Have a look here https://apps.fedoraproject.org/packages/midori

**Comment by ohreally** [comment]
Made the mistake of installing Qubes OS, which is largely based on Fedora, but always behind. Hoping to find find some time soon to switch to something decent.
