### ISSUE TITLE
Apturl broken

### ISSUE THREAD

**Issue by rbtylee** [midori-browser/core#234]
Bodhi linux ( ubuntu based)  has shipped with Midori as the only web browser installed by default probably since the beginning of Bodhi. For bodhi linux 5.0 this is version 0.5.11.  Hearing about the 7.0 release I was willing to give it a try and maybe packaging it for BL 5.0. Midori v0.5.11 doesn't satisfy most of our users who go on to install another web browser, FF or Chrome or whatnot. Taking a look at version 7.0 I find that apturls no longer work. That is a necessity to Bodhi as our online app center depends upon it. 

Trying to eliminate a bodhi specific issue with apturl, I installed midori 7.0 and apturl on lubuntu and apturls fail there also. 

No relevant errors displayed in a terminal but the error displayed in midori is:

```
Midori can't find the page you're looking for
The page located at “(null)” cannot be found. Check the web address for misspelled words and try again.

The URL can’t be shown
```

**Comment by kalikiana** [comment]
Indeed I can reproduce with https://www.bodhilinux.com/a/handbrake/ and I'm getting the aforementioned error. Apparently this case should be handled in the load error case. See the related PR for the fix.

**Comment by rbtylee** [comment]
Much thanks. Briefly tested here and it is working :D

**Comment by kalikiana** [comment]
Thanks for testing!
