### ISSUE TITLE
Question(not issue) How to build Midori 0.5.11 for Windows

### ISSUE THREAD

**Issue by arvindpro** [midori-browser/core#239]
Hi

I have the tarball for Midori browser 0.5.11 - how do I build this for windows.
Also which IDE/OS do you use for Midori development? I would prefer to use VC++ 6(old version :) ) for working on Midori- is it possible to do this? 

Another question- I want to work with C/C++ only- what I understand is I can compile Vala files to C Code. But my question is this- how do I integrate the VALA files into the overall project after their code is converted to C Code.

One final question- the 0.5.11 release is the last one for WIndows/Mac, right? Is it (theoretically) possible to build Midori from source for version 7 or 6? ( I meant build it for Windows or Mac)

One more question- how to include support for Flash and custom CA(SSL Certificate Authority) built-in in the browser? So that the end user need not worry about running Flash content?

Yours sincerely,
Arvind.

**Comment by kalikiana** [comment]
Hey @arvindpro 

- Development mostly happens on Linux using VIM or Geany but that is a matter of taste of course. I honestly don't know if VC 6 still works... it's been several years that I've used it.
- CMake takes care of building the project and turning Vala into executable code (and behind the scenes into C code). You shouldn't need to worry about it.
- We have an issue where we're discussing the current status of building 7 or git master for that matter on Windows, which is #209 and we will figure out what the best option is - you are very welcome to join the conversation! - 7 *may* build on MacOS, unfortunately the person looking into it isn't available atm and we need someone with an actual Macbook* or MacMini before there's an answer to that. Currently we decided to prioritize Windows just for that reason.
- Flash and SSL questions might depend on the answer of the previous question... or are you looking to have a customized bundle? I would suggest a separate issue where we can discuss if it's a feature request, or something that needs documenting etc.
