### ISSUE TITLE
Question about speed dial

### ISSUE THREAD

**Issue by voidpin** [midori-browser/core#241]
Hi all,
I used to use Midori a few years ago and I'm very happy its back!
Thank you guys!
Running version 7.0 on NetBSD 8.0.

I wonder if there is a way of configuring the Speed Dial? I would like to change background color, size of the icons (they are huge and pixeled) and be able to choose what pages show there. Maybe a few lines to be added to ~/.config/midori/config ??

I'm really enjoying this browser although, sometimes I get a bump on the cpu usage to extreamly high loads. Don't know if anyone else is experiencing this?!

Thanks

**Comment by asc-soc** [comment]
When Midori is built, data/speed-dial.html and data/about.css are the relevant files.
Theoretically this would be addressed by user stylesheets (as per https://wiki.xfce.org/midori/faq), but see #123 .

**Comment by voidpin** [comment]
Thx!
So currently, I should do this from the src tree and compile the binary locally on my machine.
But, if I read you right, it might be a feature  in future editions.
