### ISSUE TITLE
Enhancement Security

### ISSUE THREAD

**Issue by Poncho09** [midori-browser/core#246]
Midori Browser is increasingly popular, for this reason you must improve your security, managing a different database to access the files or implementing a cryptographic system. I think what an database Web SQL Storage it could be the solution.

This Web SQL storages the information of the history, bookmark, among others I think that this option should not affect the performance of the browser but on the contrary it would increase it.

**Comment by kalikiana** [comment]
Can you elaborate a bit on how this would enhance security compared to sqlite?

Encryption has been considered before. A widely accepted notion is however that the user's computer/ phone should be encrypted, and this is very easy these days. So adding another layer doesn't necessarily add anything here.

**Comment by kalikiana** [comment]
I'm closing this issue since there's no workable proposal.
