### ISSUE TITLE
User agent show Midori 6 and not 8

### ISSUE THREAD

**Issue by AngryPenguinPL** [midori-browser/core#295]
Hi,
I've compiled Midori 8.0 today on OpenMandriva and I see that user agent instead of version 8, shows version 6.
This is detected user agent:

> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.0 Safari/605.1.15 Midori/6

I do not know if this is intentional, or maybe an issue in Midori or in my build.

**Comment by kalikiana** [comment]
This is a privacy measure. The user agent is not updated along with the release version because
- changing the user agent increases fingerprintability
- Midori itself doesn't ship its own engine but uses WebKit

I hope this answers the question. Perhaps this should be documented better?

**Comment by AngryPenguinPL** [comment]
Thanks. I understand. 
I'm closing the report.
