### ISSUE TITLE
Will midori-browser.org ever have a forum?

### ISSUE THREAD

**Issue by screeguy** [midori-browser/core#296]
I need "readerview" functionality and something akin to a Scrapbook plugin before I'll consider using any browser. I can't find anyplace that discusses specific features available on Midori. A discussion forum on the website would be useful for answering questions like this and other discussions.

**Comment by Poncho09** [comment]
Midori Browser a few months ago it has a forum or groups only that were not yet available refresh the website please.

**Comment by Poncho09** [comment]
![captura de pantalla_2019-03-07_14-39-51](https://user-images.githubusercontent.com/12289753/53984229-f050e580-40e6-11e9-85c9-984cbfc690ff.png)

**Comment by bubblemonstersg** [comment]
The Midori website's code has already been archived here at Github.

**Comment by Poncho09** [comment]
The website code is not found on github since we use wordpress
