### ISSUE TITLE
Compile flag for not using gnome-dbus

### ISSUE THREAD

**Issue by gearhead** [midori-browser/core#300]
I have compiled 7.0 for arch arm using the arch PKGBUILD file. This is for a Kiosk and not a desktop so I have removed some functionality. The only edit I made to the original pkgbuild was to remove the zeitgeist
with this flag I found in another PKGBUILD for an older version:
-DUSE_ZEITGEIST=0 

Can I disassociate gdbus from it? I get this in my journal, I guess, because gnome is not installed:
 midori[710]: g_dbus_connection_emit_signal: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

Can this be resolved with a compile time flag?

**Comment by kalikiana** [comment]
GNOME is not required to run Midori. We have a lot of happy users on Xfce and other environments. 😉️ That said, DBus is integral to single instance logic of the Glib.Application API and sending notifications.

Can you perhaps provide more context? Is Midori not running correctly or is it failing at runtime?


P.S. there's a few command line options for kiosk use cases eg. `-a`, `-i` and `-e` that you may wanna look into, although these really have nothing to do with DBus issues.

**Comment by gearhead** [comment]
It is running just fine as full screen on matchbox wm. When I look at the logs, though, I see this repeated every time it launches and was guessing it was because I'm not running Gnome. I have built 7.0 and now 8.0 with the 'no zeitgeist' flag set and was wondering if I should compile it with other flags to make it more appropriate for a kiosk/embedded environment. I was not able to find what flag options there are in my perusal of the code. I'm open to any suggestions. This install is Arch Linux on a Pi2/3 (armv7h)

**Comment by kalikiana** [comment]
Midori 8 has no Zeitgeist flag or any other ones. You'll probably find that CMake is complaining about an unused flag if you look at the build log.

I would suggest to run Midori with `G_DEBUG=fatal-warnings gdb ./midori` to make it abort when those DBus errors are emitted, and inspect what's causing it and we can investigate from there.

**Comment by kalikiana** [comment]
I'm going to close this issue since without any more details we can't move forward and it's unknown what problem is being reported here. Feel free to come back with more details, though, or ask for help in IRC or Telegram.
