### ISSUE TITLE
Compile with bookmarks manager support

### ISSUE THREAD

**Issue by VanackSabbadium** [midori-browser/core#302]
Hi everyone, i searched for the answer to my question but i didn't find any.
My question is: is it possible to compile the latest Midori version (8.0) with bookmarks support?

I'm currently using the 0.5.11 version which has bookmarks support but crashes frequently. So i want a new version but i also want bookmarks support (at least).
Can i do it or is it currently unsupported?

Thanks.

**Comment by kalikiana** [comment]
A full-blown bookmarks manager is currently under discussion. What bookmarking-related feature are you after mostly? As a rule of thumbs it's easier to plan a concrete feature subset in each issue.

**Comment by VanackSabbadium** [comment]
Well, i just want bookmarks, nothing else. The latest release doesn't support them...

**Comment by kalikiana** [comment]
See #79 for the panel. I'll close this issue since there's no workable feature request or bug report.
