### ISSUE TITLE
dependency on gobject-introspection makes cross-compile impossible

### ISSUE THREAD

**Issue by stefson** [midori-browser/core#303]
I'm not sure for what you need introspection support? It makes any attempt of non-native compiling impossible, as gobject-introspection is the most cross-unfriendly package I've ever encountered. And being itself a compiler, overcoming these problems seems not solving any problem. 

The midori code itself isn't that demanding to compile, neither is gobject-introspection. But the issue here it's webkit-gtk as a base, which can't be cross-compiled with the gobject-introspection bindings. Midori-0.5 used to work fine without them, now with never versions it seems to be a hard dependency which can't be avoided.  

So, do you think you could possibly add a compile switch to disable the need of gobject-introspection? midori is highly efficent on low-memory systems at runtime, but without a cross-compile ability it isn't worth a dev's time to port it.

**Comment by kalikiana** [comment]
Introspection is strictly speaking optional so we could allow building without it.

If I understand correctly removing WebKit from the public API would also help the problem at hand, and avoid adding a build option. Although this would require more work.
