### ISSUE TITLE
[question] when will this browser be "ready" for the debian based desktops and repos?

### ISSUE THREAD

**Issue by fightthepower** [midori-browser/core#310]
I went to  https://www.midori-browser.org/ to download the debian package. But the link is not showing any download page and it seems that this browser is still in development. Any idea when the completed version of the browser gonna release, a time frame would be better.  Are there any plans to use apt for installation?

**Comment by Poncho09** [comment]
We were making some updates on the website but it is ready, you can access from midori-browser.org/download.

Thanks for you report

**Comment by fightthepower** [comment]
I dont use snap in my machine will there be a `apt install` mode available or planning to do it.

**Comment by kalikiana** [comment]
Midori is available in the Debian archives:

https://packages.debian.org/search?suite=all&searchon=names&keywords=midori
