### ISSUE TITLE
Linux distros aren't updating WebKit, making web browsers and email clients vulnerable

### ISSUE THREAD

**Issue by kiwi0fruit** [midori-browser/core#315]
From February 2016 [**article**](https://www.pcworld.com/article/3034014/linux-distros-arent-updating-webkit-making-web-browsers-and-email-clients-vulnerable.html).

Is this problem still relevant in 2019?

**Comment by kalikiana** [comment]
It really depends on your distribution. It's normal for packages to stay at the last major version. WebKit, Firefox and Chromium are more commonly exempt from this policy these days. Ubuntu and Fedora would be examples of distros upgrading these packages to the latest major version.
