### ISSUE TITLE
High CPU usage.

### ISSUE THREAD

**Issue by rvlander** [midori-browser/core#323]
It is a fresh install of Midori 8.0 on Arch.
Steps to reproduce:
* Open midori and go to whatever website (ex. archlinux.org)
* CPU usage rises at 100%
* Open a second tab to whatever website
* CPU usage is back to normal

It only happens when Midori does not directly load a website.

**Comment by voidpin** [comment]
Same on NetBSD, but random behaviour.
Also launching top shows that the browser is using only one of the cpu cores. Firefox destributes the load among all cores.
