### ISSUE TITLE
Proposal for using OBS

### ISSUE THREAD

**Issue by Poncho09** [midori-browser/core#324]
- Unify packaging in one place
- Automatic reporting of errors for each distro-specific build
- Support multiple architectures
- Provide native packages for all distros
  - Deb: Ubuntu, Debian, Astian OS
  - RPM: OpenSUSE, RHEL
  - Slackware
  - Solus

**Comment by Poncho09** [comment]
What do you think communy?

**Comment by kalikiana** [comment]
A PDF doesn't seem like the best way to share a proposal on GitHub 😉️

**Comment by kalikiana** [comment]
As for my opinion on this:

- Users want packages in their distro's archive first of all. Third-party repos are hard to discover and naturally a security concern.
- Packaging is a lot of work. Who's going to maintain and test all of these packages?
- Multiple architectures... I don't see how this is a new feature

I'd focus on FlatPak, AppImage, Snap, formats which aren't provided by distro maintainers and provide benefits different to native packages.

**Comment by Poncho09** [comment]
Excellent questions my friend,

Multiple architectures, users and distributions oriented ARM7 and ARM8, Raspberry for various projects they need an optimal browser and better option than Midori Browser, other than that we need an optimal browser for more than 3000K OLPC for Latam.

In the Spanish community of Telegram some users willing to work in the maintenance of native packages, because native packages? because there are distributions without the famous systemd and the packages like Snap and Flatpak only work correctly with the systemd and we must also cover those distributions. I know that these formats are the future but there are users in distros (rebel users hehehehehe) and we must provide a light solution.

**Comment by voidpin** [comment]
As long as the source is available, we (the rebel users) can package it ourselfs. I use NetBSD and will keep doing so. Not going back to systemd.
