### ISSUE TITLE
video streaming

### ISSUE THREAD

**Issue by voidpin** [midori-browser/core#329]
Hi,
Been running Midori on NetBSD for a few months now, currently version 8.0
I'm very happy with it and would like to keep using it as my only browser. But, I can't stream any media... I've installed gstreamer and ffmpeg. Am I missing something else that might be needed? Like, gstreamer plugins? In which case, what would those be? There're 38 plugin packages available!! I don't care about Youtube, but it would be nice to stream tv.
TIA

**Comment by iamleot** [comment]
Hello @voidpin,
Yes, probably needed `gst-plugins1-*` packages are not installed.
Possible starting point is to install:

 - gst-plugins1-bad
 - gst-plugins1-good
 - gst-plugins1-libav
 - gst-plugins1-ugly
 - gst-plugins1-vpx
 - gst-plugins1-x264

...and corresponding audio output (e.g. for oss):

 - gst-plugins1-oss

**Comment by krytarowski** [comment]
Is there gst-plugins1-sunaudio?

**Comment by niacat** [comment]
There's no sunaudio plugin in pkgsrc, and none that I can find in upstream gstreamer.

I would potentially be interested in writing one, but as far as I can see there's not much reason to without WebRTC support in webkit-gtk browsers. The OSS plugin is write-only, as far as I can see, so it'd need to be modified or rewritten for microphone recording support.

**Comment by voidpin** [comment]
gst-plugins1-vpx is not available as a binary package, although it's available in pkgsrc. As for gst-plugins1-sunaudio, I could not find it. The other are installed. Audio works, but the video doesn't display :(file:///home/pin/2019-06-10-160832_1600x900_scrot.png

**Comment by voidpin** [comment]
Thanks for your input @iamleot and @krytarowski
Youtube doesn't work, but I don't really care about that. Installing gst-plugins1-bad, -libav, -ugly, -x264
while, I already had -oss and -good installed solved the issue on other video streaming platforms. Thx!
closing this issue :)

**Comment by voidpin** [comment]
Short update, the following packages are needed:
gst-plugins1-base
gst-plugins1-good
gst-plugins1-libav
gst-plugins1-oss

Regards and thx!

**Comment by kalikiana** [comment]
@voidpin Could this be fixed in the packaging? It should probably be whatever means `strongly recommended and installed by default` in the package format

**Comment by voidpin** [comment]
Yes, you're probably right. Actually, the needed packages are gst-plugins1-base, gst-plugins1-good, gst-plugins1-libav and gst-plugins1-oss.
Maybe, I should file a request.
