### ISSUE TITLE
Slash key ("/") in addressbar opens in-page search

### ISSUE THREAD

**Issue by asc-soc** [midori-browser/core#364]
On pressing the slash key ("/") when the addressbar has focus does not add the slash to the address text field, but opens the in-page search dialog instead. Input of any URI with slashes in it is impossible.
This is caused by assigning the win.find method to the slash hotkey (the secondary, primary is Ctrl-F).

**Comment by kalikiana** [comment]
This seems to be a regression. This was working correctly before. Single keys shouldn't activate when a text input field has the focus. I suspect #336.

**Comment by asc-soc** [comment]
> This seems to be a regression. This was working correctly before. Single keys shouldn't activate when a text input field has the focus. I suspect #336.

I can confirm #336. This also affects other keys, like backspace.

**Comment by asc-soc** [comment]
> This seems to be a regression. This was working correctly before. Single keys shouldn't activate when a text input field has the focus. I suspect #336.

I took a different path to solve this in another pull request.
May have other yet unknown side effects …

**Comment by Mirppc** [comment]
I can confirm this happened on Opensuse Tumbleweed arm 64 repo (mainline).  Had this happen when trying to do a Nextcloud demo on a RPI and we needed to do localhost/nextcloud and when we got to the / the search opened the search.  Tested on Leap 15.1 on a X86_64 laptop and no such issues.

**Comment by DasJott** [comment]
This is still an issue? The Browser is not usable this way...

**Comment by asc-soc** [comment]
> This is still an issue? The Browser is not usable this way...

There was a fix in #366 .

**Comment by SergeiMinaev** [comment]
Still an issue. Midory 9.0, Gentoo Linux.

**Comment by BringWookieToMe** [comment]
I have the same finding on:
```
$ slapt-get --show midori
Package Name: midori
Package Mirror: http://www.slackel.gr/repo/i486/current/
Package Priority: Custom
Package Location: ./slackel/openbox
Package Version: 9.0-i586-1dj
```

**Comment by Drejzer** [comment]
Sittl an issue, Manjaro Linux,
pacman -Qi midori:
```Name            : midori
Version         : 9.0-2
Description     : Lightweight web browser
Architecture    : x86_64
URL             : https://midori-browser.org/
Licenses        : LGPL
Groups          : None
Provides        : None
Depends On      : aria2  gcr  libarchive  libpeas  libxss  webkit2gtk  zeitgeist
Optional Deps   : gst-plugins-base: HTML5 OGG videos support [installed]
                  gst-plugins-good: HTML5 H264 and WebM videos support [installed]
                  gst-libav: HTML5 H264 videos support [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 3,93 MiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : wto, 7 lip 2020, 17:07:22
Install Date    : wto, 20 paź 2020, 14:44:56
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature```

**Comment by alspitz** [comment]
This is still an issue for me as well, on Arch with Midori 9.0-3. But it looks like development here has died and has moved to https://gitlab.com/midori-web/midori-desktop, where it seems to be a completely revamped browser.
