### ISSUE TITLE
user addons missing in extensions menu

### ISSUE THREAD

**Issue by fixerivan** [midori-browser/core#372]
tried midori from ubuntu 18.04 packages and also build from git 

in both cases in extensions there is no user addons option

![Screenshot from 2019-09-10 22-53-23](https://user-images.githubusercontent.com/29037777/64649807-f91bce80-d41d-11e9-9978-33ac5b7376e7.png)

**Comment by kalikiana** [comment]
Thanks for filing the bug report.

See #123 for an existing issue about this. I think we'll want to prioritize this for the next release. It needs some architectural enhancements, though.
