### ISSUE TITLE
Just wanted to say thx...

### ISSUE THREAD

**Issue by voidpin** [midori-browser/core#375]
...for fixing the issue with the high cpu-loads that were present on previous issues of the browser.
Also, github no longer complains about running an unsupported browser. So, thank you for that as well.
Strange issue that you already might be aware of, though. Backspace doesn't erase the url on the bar, but goes back one page. Have to use deleat to clear the url instead.
Once again thank you for this release.

Running Midori-9.0 on NetBSD-9.0_BETA as my only web browser :)

**Comment by kalikiana** [comment]
Very happy to read your thank you note :smile_cat: 

I think the issue with backspace you're referring to is part of #364. There's a branch in the works that will fix this.

**Comment by voidpin** [comment]
Yes, that's the one.
Closing this issue now
