### ISSUE TITLE
midori is not recognizing flash

### ISSUE THREAD

**Issue by hussam-dh** [midori-browser/core#399]
Hello,
I have fedora 25 with midori 0.5.11 and flash support is working fine, yesterday I installed fedora 31 with midori 9 on another box, I tried every post all over the internet and I couldn't make midori 9 recognize flash.
so if there is any tips I would be grateful. I mean like how to guide midori to the location of libflashplayer.so?, and any other piece of info that could help me.

Regards

**Comment by darkshram** [comment]
Not really a Midori issue. Webkitgtk (backend of Midori) stopped supporting NPAPI plugins since version 2.25.3. Fedora 31 uses Webkitgtk 2.26.x. Everybody is supposed to have deprecated Flash in favor of HTML5. Also, Flash will reach EOL this year (2020).

**Comment by hussam-dh** [comment]
Thanks for the response and the valuable information.
