### ISSUE TITLE
Is Midori dead?

### ISSUE THREAD

**Issue by ghost** [midori-browser/core#412]
Hi!
It will soon be one year since the latest release, hence the question.
Is Midori dead? Again?

Thx for any info on the state of things.

**Comment by hoper-a11y** [comment]
> Hi!
> It will soon be one year since the latest release, hence the question.
> Is Midori dead? Again?
> 
> Thx for any info on the state of things.

I wonder the same here.

**Comment by NRG-600** [comment]
No I don't think so

**Comment by ghost** [comment]
Could you be more specific? Last commit Oct 12, 2019.
I used to use `Midori` as my default browser on NetBSD but, had some issues with the behavior of the URL bar. Been waiting for a new release for one year now.

**Comment by NRG-600** [comment]
I do use Midori on my Linux mint machine and yup I also faced that URL bar problem. 

I develop Midori for Android not for  Linux PC or any other kind of desktop machines, 

if you wanna try Midori on Android download Midori Next

**Comment by ghost** [comment]
I think it merged with a company: https://astian.org/midori/2020/05/23/migrate-to-astian-ecosystem/

**Comment by ghost** [comment]
@NRG-600 Thanks but, I was asking about the desktop version. I might try in on Android though.
@NotHenryOlson I can only see pre-packed binaries and "portable" platform version. The problem is, these are not portable at all, I need the source-code to build in on NetBSD. All the releases listed there are useless to me but, thanks anyway.

**Comment by ghost** [comment]
Ok! I'm closing this...
5 days, no official answer, it looks most definitely dead to me.
Its a pity :(
