### ISSUE TITLE
Is it dead??

### ISSUE THREAD

**Issue by yurikodesu** [midori-browser/core#457]
Are you guys planning to continue development?

**Comment by mikwee** [comment]
I have some bad news for you. They did... but not well. They merged with the "Astian Foundation" in 2019, where you can download the "new" Midori, which is built with Electron instead of GTK (i.e. not lightweight) and includes spyware. So yes, Midori is dead. Or at least, the good Midori. RIP

**Comment by yurikodesu** [comment]
> I have some bad news for you. They did... but not well. They merged with the "Astian Foundation" in 2019, where you can download the "new" Midori, which is built with Electron instead of GTK (i.e. not lightweight) and includes spyware. So yes, Midori is dead. Or at least, the good Midori. RIP

Oh sad : (

**Comment by yurikodesu** [comment]
ill close this now
