### ISSUE TITLE
startup failure after latest update `GLIBC_2.38 not found` 

### ISSUE THREAD

**Issue by shantanugadgil** [midori-browser/core#471]
Looks like the browser is being compiled and linked on a newer glibc

I get the following when using CentOS 9 Stream (my glibc is `2.34`)

```
/full/path/midori: /lib64/libc.so.6: version `GLIBC_2.38' not found (required by /full/path/midori)
/full/path/midori: /lib64/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /full/path/midori)
```

**Comment by vandys** [comment]
If you want help with getting Vala-based Midori compiled on CentOS, ping me.  --Andy
