### ISSUE TITLE
Re-implement single-website "app" mode

### ISSUE THREAD

**Issue by kalikiana** [midori-browser/core#48]
- The CLI switch `-a/ --app` initiates "app" mode.
- Browser contains basically a single "pinned" tab.
- New tabs or windows can't be opened (except via `-e/ --execute`).
- Keyboard shortcuts aren't available.
- Context menus aren't available.
- Fullscreen mode is unavailable (except via `-e/ --execute Fullscreen`).

**Comment by asc-soc** [comment]
Fullscreen in app mode (with -e fullscreen on command line) does not seem to work.
I tried both "midori -a <URL> -e fullscreen" and "midori -e fullscreen -a <URL>".
